# Generated by Django 4.2.24 on 2026-06-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('half_paid', '半薪'), ('unpaid', 'Unpaid')], default='unpaid', max_length=30, verbose_name='Is Paid'),
        ),
    ]
