# Generated by Django 4.2.24 on 2026-06-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_jobposition_default_role'),
        ('horilla_automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailautomation',
            name='condition',
            field=models.TextField(verbose_name='Trigger Condition'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='mail_details',
            field=models.CharField(help_text='Fill mail template details(reciever/instance, `self` will be the person who trigger the automation), `As template` option will sent instead of the mail template', max_length=250, verbose_name='Mail Details'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.horillamailtemplate', verbose_name='Mail Template'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='model',
            field=models.CharField(choices=[], max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='template_attachments',
            field=models.ManyToManyField(blank=True, related_name='template_attachment', to='base.horillamailtemplate', verbose_name='Template Attachments'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='trigger',
            field=models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('on_delete', 'On Delete')], max_length=10, verbose_name='Trigger'),
        ),
    ]
