# Generated by Django 4.2.24 on 2026-05-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': '政策', 'verbose_name_plural': '公司政策'},
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='employee_id',
            field=models.ManyToManyField(to='employee.employee', verbose_name='員工清單'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='employee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank_details', to='employee.employee', verbose_name='員工'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_work_info', to='employee.employee', verbose_name='員工'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='employee_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='員工'),
        ),
    ]
