# Generated by Django 4.2.24 on 2026-05-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_groupactivestatus'),
        ('employee', '0002_alter_policy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='月薪'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='job_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.jobrole', verbose_name='職級'),
        ),
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='salary_hour',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='時薪'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='月薪'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='job_role_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.jobrole', verbose_name='職級'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='salary_hour',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='時薪'),
        ),
    ]
