# Generated by Django 4.2.24 on 2026-05-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('allocated_days', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Allocated Days')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Used Days')),
                ('carried_over', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Carried Over from Prev Year')),
                ('carry_over_expire', models.DateField(blank=True, null=True, verbose_name='Carry-over Expire Date')),
                ('source', models.CharField(choices=[('annual_reset', '每年 1/1 重置'), ('six_month_grant', '滿 6 個月補給'), ('carry_over', '遞延進來')], max_length=20, verbose_name='Source')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='think4u_annual_leave', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Annual Leave Record',
                'verbose_name_plural': 'Annual Leave Records',
                'ordering': ['-year', 'employee_id'],
                'unique_together': {('employee', 'year', 'source')},
            },
        ),
    ]
