# Generated by Django 4.2.24 on 2026-05-26 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('think4u', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField(verbose_name='Overtime Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending_employee', '待員工確認'), ('employee_confirmed', '員工已確認'), ('employee_rejected', '員工拒絕'), ('pending_hr', '待 HR 核准'), ('hr_approved', 'HR 已核准'), ('hr_rejected', 'HR 駁回'), ('cancelled', '已取消')], default='pending_employee', max_length=30, verbose_name='Status')),
                ('employee_note', models.TextField(blank=True, null=True, verbose_name='Employee Note')),
                ('hr_note', models.TextField(blank=True, null=True, verbose_name='HR Note')),
                ('employee_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_assigned_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_assignments', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Overtime Assignment',
                'verbose_name_plural': 'Overtime Assignments',
                'ordering': ['-overtime_date', '-created_at'],
            },
        ),
    ]
