# Generated by Django 4.2.24 on 2026-05-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('base', '0009_jobposition_default_role'),
        ('auth', '0013_user_is_new_employee'),
        ('think4u', '0002_overtimeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', '請假'), ('overtime', '加班')], max_length=20, verbose_name='申請類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='base.jobposition', verbose_name='適用職位')),
            ],
            options={
                'verbose_name': '審核流程',
                'verbose_name_plural': '審核流程',
                'ordering': ['job_position__department_id', 'job_position__job_position', 'request_type'],
                'unique_together': {('job_position', 'request_type')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='順序')),
                ('approver_type', models.CharField(choices=[('direct_manager', '直屬主管'), ('department_head', '部門主管'), ('role', '指定角色'), ('employee', '指定員工'), ('hr', 'HR')], max_length=30, verbose_name='審核人類型')),
                ('approver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_as_approver', to='employee.employee', verbose_name='指定員工')),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to='auth.group', verbose_name='指定角色')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='think4u.approvalworkflow', verbose_name='所屬流程')),
            ],
            options={
                'verbose_name': '審核關卡',
                'verbose_name_plural': '審核關卡',
                'ordering': ['workflow_id', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
    ]
