# Generated by Django 4.2.24 on 2026-05-28 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('think4u', '0003_approvalworkflow_approvalstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='request_type',
            field=models.CharField(choices=[('leave', '請假'), ('overtime', '加班'), ('punch_correction', '補打卡')], max_length=20, verbose_name='申請類型'),
        ),
        migrations.CreateModel(
            name='PunchCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='補打卡日期')),
                ('requested_check_in', models.TimeField(blank=True, null=True, verbose_name='補的上班時間')),
                ('requested_check_out', models.TimeField(blank=True, null=True, verbose_name='補的下班時間')),
                ('reason', models.TextField(verbose_name='申請事由')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已駁回'), ('applied', '已套用'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('current_step_order', models.PositiveSmallIntegerField(default=1, verbose_name='目前審核關卡')),
                ('decisions', models.JSONField(blank=True, default=list, verbose_name='審核記錄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_corrections', to='employee.employee', verbose_name='員工')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_correction_requests', to='think4u.approvalworkflow', verbose_name='套用流程')),
            ],
            options={
                'verbose_name': '補打卡申請',
                'verbose_name_plural': '補打卡申請',
                'ordering': ['-target_date', '-created_at'],
            },
        ),
    ]
