# Generated by Django 4.2.24 on 2026-05-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_is_new_employee'),
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('think4u', '0004_alter_approvalworkflow_request_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date', models.DateField(verbose_name='加班日期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('reason', models.TextField(verbose_name='加班事由')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已駁回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('current_step_order', models.PositiveSmallIntegerField(default=1, verbose_name='目前審核關卡')),
                ('decisions', models.JSONField(blank=True, default=list, verbose_name='審核記錄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_applications', to='employee.employee', verbose_name='員工')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_applications', to='think4u.approvalworkflow', verbose_name='套用流程')),
            ],
            options={
                'verbose_name': '加班申請',
                'verbose_name_plural': '加班申請',
                'ordering': ['-overtime_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access', to='auth.group', verbose_name='角色')),
            ],
            options={
                'verbose_name': '後台存取角色',
                'verbose_name_plural': '後台存取角色',
            },
        ),
    ]
