# Generated by Django 4.2.24 on 2026-05-28 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('think4u', '0005_overtimeapplication_adminaccessgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveGrantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='申請天數')),
                ('reason', models.TextField(verbose_name='事由')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='leave_grants/', verbose_name='證明文件')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核發'), ('rejected', '已駁回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('granted_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='核發天數')),
                ('hr_note', models.TextField(blank=True, default='', verbose_name='HR 批註')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_grants_decided', to=settings.AUTH_USER_MODEL, verbose_name='審核人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_grant_requests', to='employee.employee', verbose_name='員工')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_requests', to='leave.leavetype', verbose_name='假別')),
            ],
            options={
                'verbose_name': '給假申請',
                'verbose_name_plural': '給假申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
