# Generated by Django 4.2.24 on 2026-05-28 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('think4u', '0006_leavegrantrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_repr', models.CharField(blank=True, default='', help_text='使用者顯示名稱（即使 User 被刪除也保留）', max_length=150)),
                ('action', models.CharField(choices=[('CREATE', '建立'), ('UPDATE', '更新'), ('DELETE', '刪除')], db_index=True, max_length=10)),
                ('model_label', models.CharField(db_index=True, help_text='app_label.ModelName', max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='UPDATE: {field: [old, new], ...}; CREATE: {field: [null, new]}; DELETE: {__deleted__: {...}}')),
                ('request_path', models.CharField(blank=True, default='', max_length=300)),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4u_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '稽核紀錄',
                'verbose_name_plural': '稽核紀錄',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_label', 'object_id'], name='think4u_aud_model_l_83216e_idx'), models.Index(fields=['timestamp'], name='think4u_aud_timesta_db7fc0_idx'), models.Index(fields=['user'], name='think4u_aud_user_id_221b9a_idx')],
            },
        ),
    ]
