# Generated by Django 4.2.24 on 2026-05-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('leave', '0001_initial'),
        ('think4u', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_years', models.PositiveSmallIntegerField(verbose_name='累積年資（滿 N 年）')),
                ('anniversary_date', models.DateField(verbose_name='獲假日')),
                ('tier_days', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='該年 tier 總天數')),
                ('grant_type', models.CharField(choices=[('anniv_small', '週年小段（當年剩餘）'), ('anniv_big', '週年大段（隔年整年）')], max_length=20, verbose_name='段類型')),
                ('days_granted', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='此段天數')),
                ('days_used', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='已使用')),
                ('start_date', models.DateField(verbose_name='可用起')),
                ('end_date', models.DateField(verbose_name='可用迄')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='employee.employee', verbose_name='員工')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t4u_allocations', to='leave.leavetype', verbose_name='假別')),
            ],
            options={
                'verbose_name': '特休配給',
                'verbose_name_plural': '特休配給',
                'ordering': ['employee_id', 'start_date'],
                'indexes': [models.Index(fields=['employee', 'leave_type', 'start_date'], name='think4u_lea_employe_68df09_idx')],
                'unique_together': {('employee', 'leave_type', 'anniversary_date', 'grant_type')},
            },
        ),
    ]
