# Generated by Django 4.2.24 on 2026-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think4u', '0009_alter_leaveallocation_grant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallocation',
            name='grant_type',
            field=models.CharField(choices=[('six_month', '滿半年（一次性 3 天）'), ('anniv_small', '週年小段（當年剩餘）'), ('anniv_big', '週年大段（隔年整年）'), ('carryforward', '遞延')], max_length=20, verbose_name='段類型'),
        ),
    ]
