# Generated by Django 4.2.24 on 2026-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think4u', '0010_alter_leaveallocation_grant_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccessgroup',
            options={'verbose_name': '角色設定', 'verbose_name_plural': '角色設定'},
        ),
        migrations.AddField(
            model_name='adminaccessgroup',
            name='can_access_admin',
            field=models.BooleanField(default=False, verbose_name='可進後台'),
        ),
        migrations.AddField(
            model_name='adminaccessgroup',
            name='force_admin_only',
            field=models.BooleanField(default=False, verbose_name='強制只能用後台'),
        ),
        migrations.AddField(
            model_name='adminaccessgroup',
            name='show_in_personal_reports',
            field=models.BooleanField(default=True, verbose_name='顯示在個人加班/請假報表'),
        ),
        migrations.AddField(
            model_name='adminaccessgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
