# Generated by Django 4.2.24 on 2026-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think4u', '0011_role_settings_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccessgroup',
            name='acts_as_superuser',
            field=models.BooleanField(default=False, help_text='勾選後，此角色成員自動取得 is_superuser/is_staff 權限', verbose_name='視同 superuser'),
        ),
    ]
