# Generated by Django 4.2.24 on 2026-05-29 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('think4u', '0012_acts_as_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.PositiveIntegerField(default=50000, verbose_name='月薪（NT$）')),
                ('dependents', models.PositiveSmallIntegerField(default=0, verbose_name='健保眷屬人數')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t4u_salary', to='employee.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '員工月薪',
                'verbose_name_plural': '員工月薪',
            },
        ),
    ]
