# Generated by Django 4.2.24 on 2026-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think4u', '0013_employee_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'verbose_name': '員工薪資', 'verbose_name_plural': '員工薪資'},
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='base_salary',
            field=models.PositiveIntegerField(default=50000, verbose_name='本薪'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='management_allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='管理加給'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='meal_allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='伙食津貼'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_addition',
            field=models.PositiveIntegerField(default=0, verbose_name='薪資加給'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='tech_management_allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='技術管理加給'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='transport_allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='交通津貼'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='monthly_salary',
            field=models.PositiveIntegerField(default=50000, verbose_name='月薪（NT$，舊）'),
        ),
    ]
