# Generated by Django 4.2.24 on 2026-05-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('think4u', '0014_salary_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsuranceDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='眷屬姓名')),
                ('relationship', models.CharField(choices=[('spouse', '配偶'), ('child', '子女'), ('parent', '父母'), ('grandparent', '祖父母'), ('other', '其他')], default='spouse', max_length=20, verbose_name='關係')),
                ('national_id', models.CharField(blank=True, default='', max_length=20, verbose_name='身分證字號')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('enroll_date', models.DateField(blank=True, null=True, verbose_name='加保起日')),
                ('is_enrolled', models.BooleanField(default=True, verbose_name='加保中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t4u_dependents', to='employee.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '健保眷屬',
                'verbose_name_plural': '健保眷屬',
                'ordering': ['employee_id', 'id'],
            },
        ),
    ]
