# Generated by Django 4.2.24 on 2026-05-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeworkinformation_basic_salary_and_more'),
        ('think4u', '0015_health_dependents'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月')),
                ('overtime_pay', models.IntegerField(default=0, verbose_name='加班費')),
                ('unused_annual_leave', models.IntegerField(default=0, verbose_name='特休未休')),
                ('birthday_gift', models.IntegerField(default=0, verbose_name='生日禮金')),
                ('dragonboat_gift', models.IntegerField(default=0, verbose_name='端午禮金')),
                ('midautumn_gift', models.IntegerField(default=0, verbose_name='中秋禮金')),
                ('expense_reimbursement', models.IntegerField(default=0, verbose_name='給付代墊公司費用')),
                ('perfect_attendance_bonus', models.IntegerField(default=0, verbose_name='全勤獎勵金')),
                ('admin_assistant_fee', models.IntegerField(default=0, verbose_name='行政助理費')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t4u_pay_extras', to='employee.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '每月變動加項',
                'verbose_name_plural': '每月變動加項',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
