# Generated by Django 4.2.24 on 2026-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think4u', '0016_monthly_pay_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='時薪'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='pay_type',
            field=models.CharField(choices=[('monthly', '月薪制'), ('hourly', '時薪制')], default='monthly', max_length=10, verbose_name='計薪方式'),
        ),
    ]
