# Generated by Django 4.2.24 on 2026-06-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('think4u', '0017_employeesalary_hourly_rate_employeesalary_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='health_insured_salary',
            field=models.PositiveIntegerField(default=0, verbose_name='健保投保薪資'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='labor_insured_salary',
            field=models.PositiveIntegerField(default=0, verbose_name='勞保投保薪資'),
        ),
    ]
