# Generated by Django 4.2.24 on 2026-05-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建於')),
                ('is_active', models.BooleanField(default=True, verbose_name='處於活動狀態')),
                ('feature', models.CharField(choices=[('employee_view', 'Default Employee View'), ('employee_detailed_view', 'Default Employee Detailed View'), ('gender_chart', 'Can view Gender Chart'), ('department_chart', 'Can view Department Chart'), ('employees_chart', 'Can view Employees Chart'), ('birthday_view', 'Can view Birthdays')], max_length=100)),
                ('filter', models.JSONField()),
                ('exclude_all', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
