# Generated by Django 4.2.24 on 2026-05-26 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_is_new_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePageVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建於')),
                ('is_active', models.BooleanField(default=True, verbose_name='處於活動狀態')),
                ('sidebar_key', models.CharField(choices=[('employee', 'Employee'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('base', 'Organization Chart')], max_length=32, verbose_name='Sidebar Module')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honsi_visibilities', to='auth.group', verbose_name='Role / Group')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': 'Role Page Visibility',
                'verbose_name_plural': 'Role Page Visibilities',
                'unique_together': {('group', 'sidebar_key')},
            },
        ),
    ]
