# Generated by Django 4.2.24 on 2026-05-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_is_new_employee'),
        ('base', '0003_rolepagevisibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepagevisibility',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='think4u_visibilities', to='auth.group', verbose_name='Role / Group'),
        ),
    ]
