# Generated by Django 4.2.24 on 2026-05-27 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_is_new_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_rolepagevisibility_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建於')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='think4u_status', to='auth.group', verbose_name='Group')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': 'Group Active Status',
                'verbose_name_plural': 'Group Active Statuses',
            },
        ),
    ]
