# Generated by Django 4.2.24 on 2026-05-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_groupactivestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepagevisibility',
            name='sidebar_key',
            field=models.CharField(max_length=64, verbose_name='Sidebar Module'),
        ),
    ]
