# Generated by Django 4.2.24 on 2026-05-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_is_new_employee'),
        ('base', '0008_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_positions', to='auth.group', verbose_name='預設角色'),
        ),
    ]
