# Generated by Django 4.2.24 on 2026-05-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建於')),
                ('is_active', models.BooleanField(default=True, verbose_name='處於活動狀態')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('format', models.CharField(choices=[('any', 'Any'), ('pdf', 'PDF'), ('txt', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=10, verbose_name='格式')),
                ('max_size', models.IntegerField(blank=True, null=True, verbose_name='Max size (In MB)')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('employee_id', models.ManyToManyField(to='employee.employee', verbose_name='員工')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '文件請求',
                'verbose_name_plural': '文件請求',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='創建於')),
                ('is_active', models.BooleanField(default=True, verbose_name='處於活動狀態')),
                ('title', models.CharField(max_length=250)),
                ('document', models.FileField(null=True, upload_to=horilla.models.upload_path, verbose_name='文件')),
                ('status', models.CharField(choices=[('requested', '已請求'), ('approved', '得到正式認可的'), ('rejected', '被拒絕')], default='requested', max_length=10, verbose_name='地位')),
                ('reject_reason', models.TextField(blank=True, max_length=255, null=True, verbose_name='拒絕原因')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='簽發日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('notify_before', models.IntegerField(default=1, null=True, verbose_name='在此日期前通知')),
                ('is_digital_asset', models.BooleanField(default=False, verbose_name='是數位資產')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('document_request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='horilla_documents.documentrequest')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='員工t')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
    ]
