# Generated by Django 4.2.24 on 2026-05-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_policy_options_and_more'),
        ('horilla_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'verbose_name': '文件請求', 'verbose_name_plural': '文件申請'},
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='員工'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='employee_id',
            field=models.ManyToManyField(to='employee.employee', verbose_name='員工清單'),
        ),
    ]
