# Generated by Django 4.2.24 on 2026-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_documents', '0002_alter_documentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('requested', '已請求'), ('approved', '已審核'), ('rejected', '被拒絕')], default='requested', max_length=10, verbose_name='地位'),
        ),
    ]
