# Generated by Django 4.2.24 on 2026-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='attendance_type',
            field=models.CharField(choices=[('office', '公司打卡'), ('field', '外勤打卡')], default='office', max_length=20, verbose_name='Attendance Type'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='field_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Field Reason'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='verification_code_used',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification Code Used'),
        ),
    ]
